pub static CRATES: [&str; 21] = [
    "PISTOL",
    "SHOTGUN",
    "UZI",
    "AUTO RIFLE",
    "GRENADE LAUNCHER",
    "AUTO GRENADIER",
    "HEAVY LAUNCHER",
    "AUTO SHOTGUN",
    "C4-ACTIVATOR",
    "FLAME THROWER",
    "MINE DROPPER",
    "9MM BULLETS (50)",
    "12MM BULLETS (50)",
    "SHOTGUN SHELLS (20)",
    "LIGHT GRENADES (15)",
    "MEDIUM GRENADES (10)",
    "HEAVY GRENADES (5)",
    "C4-EXPLOSIVES (5)",
    "GAS (50)",
    "MINES (5)",
    "ENERGY",
];
